name: Deploy Opsap Services

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  check-changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'apps/opsap/backend/**'
              - 'packages/opsap/**'
              - 'packages/shared/**'
            frontend:
              - 'apps/opsap/frontend/**'
              - 'packages/opsap/**'
              - 'packages/shared/**'

  deploy-backend:
    name: Deploy Backend
    needs: check-changes
    if: needs.check-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "opsap-backend"
          entrypoint: "apps/opsap/backend/main.ts"
          import-map: "./deno.json"

  deploy-frontend:
    name: Deploy Frontend
    needs: [check-changes, deploy-backend]
    if: needs.check-changes.outputs.frontend == 'true' || needs.check-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: canary

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: deno install
        working-directory: apps/opsap/frontend

      - name: Build frontend
        run: deno task build
        working-directory: apps/opsap/frontend

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "opsap-frontend"
          entrypoint: "mod.ts"
          root: "apps/opsap/frontend/build"
